### ISSUE TITLE
Tests are dirty

### ISSUE THREAD

**Issue by zenspider** [BrendanThompson/rb-scpt#6]
On my warnings branch:

```
/Users/ryan/.rbenv/versions/2.4.1/bin/ruby extconf.rb
create /Users/ryan/Work/git/BrendanThompson/rb-scpt/src/osx_ruby.h ...
create /Users/ryan/Work/git/BrendanThompson/rb-scpt/src/osx_intern.h ...
creating Makefile
make
compiling src/SendThreadSafe.c
src/SendThreadSafe.c:362:16: warning: use of logical '&&' with constant operand [-Wconstant-logical-operand]
  if (sendMode && kAEWaitReply) {
               ^  ~~~~~~~~~~~~
src/SendThreadSafe.c:362:16: note: use '&' for a bitwise operation
  if (sendMode && kAEWaitReply) {
               ^~
               &
src/SendThreadSafe.c:362:16: note: remove constant to silence this warning
  if (sendMode && kAEWaitReply) {
              ~^~~~~~~~~~~~~~~
1 warning generated.
compiling src/rbae.c
src/rbae.c:493:9: warning: 'LSFindApplicationForInfo' is deprecated: first deprecated in macOS 10.10 - Use LSCopyApplicationURLsForBundleIdentifier instead. [-Wdeprecated-declarations]
  err = LSFindApplicationForInfo(inCreator,
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/LSInfoDeprecated.h:785:1: note: 'LSFindApplicationForInfo' has been explicitly marked deprecated here
LSFindApplicationForInfo(
^
src/rbae.c:501:9: warning: 'FSRefMakePath' is deprecated: first deprecated in macOS 10.8 [-Wdeprecated-declarations]
  err = FSRefMakePath(&outAppRef, path, PATH_MAX);
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Files.h:4086:18: note: 'FSRefMakePath' has been explicitly marked deprecated here
extern OSStatus  FSRefMakePath(const FSRef *ref, UInt8 *path, UInt32 pathBufferSize)     __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0, __MAC_10_8, __IPHONE_NA, __IPHONE_NA);
                 ^
src/rbae.c:514:9: warning: 'FSPathMakeRef' is deprecated: first deprecated in macOS 10.8 [-Wdeprecated-declarations]
  err = FSPathMakeRef((UInt8 *)StringValuePtr(path), &appRef, NULL);
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Files.h:4115:18: note: 'FSPathMakeRef' has been explicitly marked deprecated here
extern OSStatus  FSPathMakeRef(const UInt8 *path, FSRef *ref, Boolean *isDirectory)        __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0, __MAC_10_8, __IPHONE_NA, __IPHONE_NA);
                 ^
src/rbae.c:517:11: warning: 'GetNextProcess' is deprecated: first deprecated in macOS 10.9 [-Wdeprecated-declarations]
    err = GetNextProcess(&psn);
          ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/HIServices.framework/Headers/Processes.h:452:1: note: 'GetNextProcess' has been explicitly marked deprecated here
GetNextProcess(ProcessSerialNumber * PSN)                     AVAILABLE_MAC_OS_X_VERSION_10_0_AND_LATER_BUT_DEPRECATED_IN_MAC_OS_X_VERSION_10_9;
^
src/rbae.c:519:11: warning: 'GetProcessBundleLocation' is deprecated: first deprecated in macOS 10.9 [-Wdeprecated-declarations]
    err = GetProcessBundleLocation(&psn, &foundRef);
          ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/HIServices.framework/Headers/Processes.h:815:1: note: 'GetProcessBundleLocation' has been explicitly marked deprecated here
GetProcessBundleLocation(
^
src/rbae.c:521:9: warning: 'FSCompareFSRefs' is deprecated: first deprecated in macOS 10.8 [-Wdeprecated-declarations]
    if (FSCompareFSRefs(&appRef, &foundRef) == noErr)
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Files.h:1850:15: note: 'FSCompareFSRefs' has been explicitly marked deprecated here
extern OSErr  FSCompareFSRefs(const FSRef *ref1, const FSRef *ref2)                     __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0, __MAC_10_8, __IPHONE_NA, __IPHONE_NA);
              ^
src/rbae.c:533:9: warning: 'GetProcessForPID' is deprecated: first deprecated in macOS 10.9 [-Wdeprecated-declarations]
  err = GetProcessForPID(NUM2INT(pid), &psn);
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/ApplicationServices.framework/Frameworks/HIServices.framework/Headers/Processes.h:930:1: note: 'GetProcessForPID' has been explicitly marked deprecated here
GetProcessForPID(
^
src/rbae.c:546:9: warning: 'FSPathMakeRef' is deprecated: first deprecated in macOS 10.8 [-Wdeprecated-declarations]
  err = FSPathMakeRef((UInt8 *)StringValuePtr(path), &appRef, NULL);
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Files.h:4115:18: note: 'FSPathMakeRef' has been explicitly marked deprecated here
extern OSStatus  FSPathMakeRef(const UInt8 *path, FSRef *ref, Boolean *isDirectory)        __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0, __MAC_10_8, __IPHONE_NA, __IPHONE_NA);
                 ^
src/rbae.c:548:3: warning: 'LSApplicationParameters' is deprecated: first deprecated in macOS 10.10 - Use NSWorkspace instead. [-Wdeprecated-declarations]
  LSApplicationParameters appParams = {0,
  ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/LSOpenDeprecated.h:151:3: note: 'LSApplicationParameters' has been explicitly marked deprecated here
} LSApplicationParameters __OSX_AVAILABLE_BUT_DEPRECATED_MSG(__MAC_10_4, __MAC_10_10, __IPHONE_NA, __IPHONE_NA, "Use NSWorkspace instead.");
  ^
src/rbae.c:553:9: warning: 'LSOpenApplication' is deprecated: first deprecated in macOS 10.10 - Use -[NSWorkspace launchApplicationAtURL:options:configuration:error:] instead. [-Wdeprecated-declarations]
  err = LSOpenApplication(&appParams, &psn);
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/LSOpenDeprecated.h:183:1: note: 'LSOpenApplication' has been explicitly marked deprecated here
LSOpenApplication(
^
src/rbae.c:709:9: warning: 'FSPathMakeRef' is deprecated: first deprecated in macOS 10.8 [-Wdeprecated-declarations]
  err = FSPathMakeRef((UInt8 *)StringValuePtr(path), &fsRef, NULL);
        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/CarbonCore.framework/Headers/Files.h:4115:18: note: 'FSPathMakeRef' has been explicitly marked deprecated here
extern OSStatus  FSPathMakeRef(const UInt8 *path, FSRef *ref, Boolean *isDirectory)        __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0, __MAC_10_8, __IPHONE_NA, __IPHONE_NA);
                 ^
11 warnings generated.
linking shared-object ae.bundle
/Users/ryan/.rbenv/versions/2.4.1/bin/ruby -w -I"lib:src/lib:." -e "ARGV.each{|f| require f}" "test/test_aemreference.rb" "test/test_appscriptcommands.rb" "test/test_appscriptreference.rb" "test/test_codecs.rb" "test/test_findapp.rb" "test/test_mactypes.rb" "test/test_osax.rb" 
Run options: --seed 51593

# Running:

EXPECTED: AEM.app.property("ctxt")
EF....FFE...F/Users/ryan/Work/git/BrendanThompson/rb-scpt/test/test_appscriptcommands.rb:121: warning: constant ::Fixnum is deprecated
..F.FEEE.E..EEFE.E

Finished in 2.795034s, 11.0911 runs/s, 38.2822 assertions/s.

  1) Error:
TC_AEMReferences#test_reference_forms:
ArgumentError: wrong number of arguments (given 0, expected 1)
    /Users/ryan/Work/git/BrendanThompson/rb-scpt/src/lib/_aem/aemreference.rb:102:in `=='

  2) Failure:
TC_Codecs#test_str [/Users/ryan/Work/git/BrendanThompson/rb-scpt/test/test_codecs.rb:104]:
--- expected
+++ actual
@@ -1,2 +1,3 @@
-"\x92\u0001\u0002\"\xAE\u00007\u0005V\u00059\u0005\t
+# encoding: ASCII-8BIT
+"\x92\x01\x02\"\xAE\x007\x05V\x059\x05\t
 \xA20;1"


  3) Failure:
TC_Codecs#test_date [/Users/ryan/Work/git/BrendanThompson/rb-scpt/test/test_codecs.rb:119]:
--- expected
+++ actual
@@ -1 +1,2 @@
-"\xFB\xF8\xC1\xBF\u0000\u0000\u0000\u0000"
+# encoding: ASCII-8BIT
+"\xFB\xF8\xC1\xBF\x00\x00\x00\x00"


  4) Failure:
TC_Codecs#test_num [/Users/ryan/Work/git/BrendanThompson/rb-scpt/test/test_codecs.rb:81]:
--- expected
+++ actual
@@ -1 +1,2 @@
+# encoding: ASCII-8BIT
 "\xF7\xFF\xFF\xFF"


  5) Error:
TC_Codecs#test_typewrappers:
ArgumentError: wrong number of arguments (given 0, expected 1)
    /Users/ryan/Work/git/BrendanThompson/rb-scpt/src/lib/_aem/typewrappers.rb:24:in `=='

  6) Failure:
TC_AppscriptCommands#test_commands_1 [/Users/ryan/Work/git/BrendanThompson/rb-scpt/test/test_appscriptcommands.rb:102]:
--- expected
+++ actual
@@ -1 +1,2 @@
-"© M. Lefèvre"
+# encoding: ASCII-8BIT
+"\xC2\xA9 M. Lef\xC3\xA8vre"


  7) Failure:
TC_AppscriptCommands#test_command_error [/Users/ryan/Work/git/BrendanThompson/rb-scpt/test/test_appscriptcommands.rb:145]:
--- expected
+++ actual
@@ -1,6 +1,7 @@
 "CommandError
 \t\tOSERROR: -1728
 \t\tMESSAGE: Can't get reference.
-\t\tOFFENDING OBJECT: app(\"/System/Library/CoreServices/Finder.app\").items[10000]
+\t\tOFFENDING OBJECT: 10000
+\t\tEXPECTED TYPE: :file_url
 \t\tCOMMAND: app(\"/System/Library/CoreServices/Finder.app\").items[10000].get()
 "


  8) Failure:
TC_MacTypes#test_file_url [/Users/ryan/Work/git/BrendanThompson/rb-scpt/test/test_mactypes.rb:66]:
--- expected
+++ actual
@@ -1 +1,2 @@
-"file://localhost/non/existent%20path"
+# encoding: ASCII-8BIT
+"file:///non/existent%20path"


  9) Error:
TC_AppscriptReferences#test_reference_forms:
ArgumentError: wrong number of arguments (given 0, expected 1)
    /Users/ryan/Work/git/BrendanThompson/rb-scpt/src/lib/rb-scpt.rb:587:in `=='

 10) Error:
TC_FindApp#test_find:
FindApp::ApplicationNotFoundError: Application "/Applications/iCal.app" not found.
    /Users/ryan/Work/git/BrendanThompson/rb-scpt/src/lib/_aem/findapp.rb:63:in `by_name'
    /Users/ryan/Work/git/BrendanThompson/rb-scpt/test/test_findapp.rb:15:in `block in test_find'
    /Users/ryan/Work/git/BrendanThompson/rb-scpt/test/test_findapp.rb:14:in `each'
    /Users/ryan/Work/git/BrendanThompson/rb-scpt/test/test_findapp.rb:14:in `test_find'

 11) Error:
TC_AppscriptNewApp#test_by_creator:
RuntimeError: Unknown property, element or command: 'name'
    /Users/ryan/Work/git/BrendanThompson/rb-scpt/src/lib/rb-scpt.rb:676:in `rescue in method_missing'
    /Users/ryan/Work/git/BrendanThompson/rb-scpt/src/lib/rb-scpt.rb:646:in `method_missing'
    /Users/ryan/Work/git/BrendanThompson/rb-scpt/test/test_appscriptcommands.rb:49:in `test_by_creator'

 12) Error:
TC_AppscriptNewApp#test_by_pid:
RuntimeError: Unknown property, element or command: 'name'
    /Users/ryan/Work/git/BrendanThompson/rb-scpt/src/lib/rb-scpt.rb:676:in `rescue in method_missing'
    /Users/ryan/Work/git/BrendanThompson/rb-scpt/src/lib/rb-scpt.rb:646:in `method_missing'
    /Users/ryan/Work/git/BrendanThompson/rb-scpt/test/test_appscriptcommands.rb:57:in `test_by_pid'

 13) Error:
TC_OSAX#test_2:
Appscript::CommandError: CommandError
		OSERROR: -10004
		MESSAGE: A privilege violation occurred.
		COMMAND: #<OSAX::ScriptingAddition name="Standardadditions" target=AEM::Application.by_path("/System/Library/CoreServices/Finder.app")>.ASCII_number("A")

    /Users/ryan/Work/git/BrendanThompson/rb-scpt/src/lib/rb-scpt.rb:542:in `_send_command'
    /Users/ryan/Work/git/BrendanThompson/rb-scpt/src/lib/rb-scpt.rb:642:in `method_missing'
    /Users/ryan/Work/git/BrendanThompson/rb-scpt/src/lib/osax.rb:569:in `method_missing'
    /Users/ryan/Work/git/BrendanThompson/rb-scpt/test/test_osax.rb:23:in `test_2'

 14) Error:
TC_OSAX#test_4:
Appscript::CommandError: CommandError
		OSERROR: -10004
		MESSAGE: A privilege violation occurred.
		COMMAND: #<OSAX::ScriptingAddition name="Standardadditions" target=AEM::Application.by_path("/System/Library/CoreServices/Finder.app")>.ASCII_number("A")

    /Users/ryan/Work/git/BrendanThompson/rb-scpt/src/lib/rb-scpt.rb:542:in `_send_command'
    /Users/ryan/Work/git/BrendanThompson/rb-scpt/src/lib/rb-scpt.rb:642:in `method_missing'
    /Users/ryan/Work/git/BrendanThompson/rb-scpt/src/lib/osax.rb:569:in `method_missing'
    /Users/ryan/Work/git/BrendanThompson/rb-scpt/test/test_osax.rb:35:in `test_4'

 15) Failure:
TC_OSAX#test_5 [/Users/ryan/Work/git/BrendanThompson/rb-scpt/test/test_osax.rb:41]:
--- expected
+++ actual
@@ -1 +1 @@
-MacTypes::Alias.path("/System/Library/CoreServices/Finder.app")
+MacTypes::Alias.path("/MyApplications/net/BitTorrent Sync.app/Contents/PlugIns/FinderExtension.appex")


 16) Error:
TC_OSAX#test_6:
Appscript::CommandError: CommandError
		OSERROR: -10004
		MESSAGE: A privilege violation occurred.
		COMMAND: #<OSAX::ScriptingAddition name="Standardadditions" target=AEM::Application.by_path("/System/Library/CoreServices/Finder.app/")>.ASCII_number("A")

    /Users/ryan/Work/git/BrendanThompson/rb-scpt/src/lib/rb-scpt.rb:542:in `_send_command'
    /Users/ryan/Work/git/BrendanThompson/rb-scpt/src/lib/rb-scpt.rb:642:in `method_missing'
    /Users/ryan/Work/git/BrendanThompson/rb-scpt/src/lib/osax.rb:569:in `method_missing'
    /Users/ryan/Work/git/BrendanThompson/rb-scpt/test/test_osax.rb:47:in `test_6'

 17) Error:
TC_OSAX#test_3:
Appscript::CommandError: CommandError
		OSERROR: -10004
		MESSAGE: A privilege violation occurred.
		COMMAND: #<OSAX::ScriptingAddition name="Standardadditions" target=AEM::Application.by_path("/System/Library/CoreServices/Finder.app")>.ASCII_number("A")

    /Users/ryan/Work/git/BrendanThompson/rb-scpt/src/lib/rb-scpt.rb:542:in `_send_command'
    /Users/ryan/Work/git/BrendanThompson/rb-scpt/src/lib/rb-scpt.rb:642:in `method_missing'
    /Users/ryan/Work/git/BrendanThompson/rb-scpt/src/lib/osax.rb:569:in `method_missing'
    /Users/ryan/Work/git/BrendanThompson/rb-scpt/test/test_osax.rb:29:in `test_3'

31 runs, 107 assertions, 7 failures, 10 errors, 0 skips
rake aborted!
Command failed with status (1): [ruby -w -I"lib:src/lib:." -e "ARGV.each{|f| require f}" "test/test_aemreference.rb" "test/test_appscriptcommands.rb" "test/test_appscriptreference.rb" "test/test_codecs.rb" "test/test_findapp.rb" "test/test_mactypes.rb" "test/test_osax.rb" ]

Tasks: TOP => default => test
(See full trace by running task with --trace)
```

It looks like a lot of this is just stale or brittle testing to begin with (master is at least as dirty... hard to tell with all the noise and the way they're run).

**Comment by BrendanThompson** [comment]
@zenspider you happy to look into this?

**Comment by zenspider** [comment]
I don't know why they're failing but they were at least as bad on master..

Do they pass for you?

**Comment by BrendanThompson** [comment]
@zenspider I got the same errors that you did. I have also branched up the repo a bit. Will do things out of `develop` now :).

**Comment by zenspider** [comment]
Where does this stand? I can’t do much with this gem without clean tests...

**Comment by BrendanThompson** [comment]
If you’re interested in picking this one up and moving the tests out, and getting them clean again?

**Comment by zenspider** [comment]
This is handled by #20
